# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    allowBrokenSymlinks: 

- script: |
    npm install
    npm test
    displayName: 'npm install and test'

- script: |
    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
    chmod +x codeql-runner-linux
    displayName: 'Get latest CodeQL package. Install on Agent.'
 
- script: |
    ./codeql-runner-linux init --repository octodemo/ghas-azure-devops-code-scanning --github-url https://github.com --github-auth $GITHUB_PAT
    displayName: 'Initialize CodeQ Executable and create a CodeQL database'

- script: |
    ./codeql-runner-linux analyze --repository octodemo/ghas-azure-devops-code-scanning --github-url https://github.com --github-auth $GITHUB_PAT --commit 92065de8b22bbfeda511d12571b66c9969ff593b --ref refs/heads/master
    displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'



